name: libopenshot-audio CI Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Download ASIOSDK
      run: |
        Invoke-WebRequest -Uri https://www.steinberg.net/asiosdk -MaximumRedirection 5 -OutFile asiosdk.zip
        unzip asiosdk.zip
        move asiosdk* asiosdk
        dir
        dir asiosdk/
    - name: Compile ZLIB
      run: |
        git clone https://github.com/madler/zlib
        pushd zlib
        cmake -B . -S . -G "Visual Studio 16 2019" -A ARM64
        cmake --build . --config Debug
        popd
    - name: Build libopenshot-audio
      run: |
        mkdir build
        pushd build
        cmake -B . -G "Visual Studio 16 2019" -A ARM64 -S .. -DCMAKE_INSTALL_PREFIX:PATH="dist" -DZLIB_INCLUDE_DIR="..\zlib" -DZLIB_LIBRARY="..\zlib\build\Debug\zlib.lib" -DASIO_SDK_DIR="..\asiosdk\common"
        cmake --build . --config Debug
        popd

    - name: Install libopenshot-audio
      run: |
        pushd build
        cmake --build . --target install -- VERBOSE=1
        popd
